# Generated by Django 6.0.6 on 2026-07-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telephone'),
        ),
    ]
