# Generated by Django 6.0.6 on 2026-07-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
