# Generated by Django 6.0.6 on 2026-07-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='default_place.png', upload_to='place_pics'),
        ),
    ]
